### ISSUE TITLE
with_seed() does not give enough randomness.

### ISSUE THREAD

**Issue by martinlindhe** [jackmott/rust-simd-noise#42]
Consider the following code.

No matter the amount of random seeds, it only generates 8 unique outputs.

```rs
// main.rs
use simdnoise::NoiseBuilder;
use sha1::{Sha1, Digest};
use rand::Rng;

use std::collections::HashMap;

fn main() {

    let width = 100;
    let height = 100;
    let mut ground = vec!(0; width * height);

    let mut subjcts = HashMap::new();

    for i in 0..10000 {

        let mut rng = rand::thread_rng();
        let seed: u32 = rng.gen();

        let noise = NoiseBuilder::fbm_2d(width, height)
            .with_seed(seed as i32)
            .generate_scaled(0., 255.);

        for i in 0..width * height {
            ground[i] = noise[i] as u8;
        }

        let mut hasher = Sha1::new();
        hasher.update(&ground);
        let result = hasher.finalize();
        let hash_s = result.encode_hex::<String>();

        use hex::ToHex;
        *subjcts.entry(hash_s).or_insert(1) += 1;
    }

    // list results
    for (key, val) in subjcts.iter() {
        println!("key_is: {} val_is: {}", key, val);
    }
}
```

```toml
// Cargo.toml
[package]
name = "simdnoise_seed"
version = "0.1.0"
edition = "2021"

[dependencies]
simdnoise = "3.1.6"
sha1 = "0.10"
hex = "0.4"
rand = "0.8"
```
